### ISSUE TITLE
Issues with steel fiber sections

### ISSUE THREAD

**Issue by manoslydakis** [rclab-auth/gidopensees#138]
Hey all,

I am working on a project where I want to make a 3D model of an offshore structure in OpenSees. I also downloaded Gid + OpenSees and I created the geometry by importing a tcl file.

At that point, I want to estimate the periods of the structure by making an eigenvalue analysis. I want to do it in 2 ways:
1. Considering elastic beam-column elements using multidimensional (nd) material (steel).
2. Considering fiber steel elements with uniaxial material Steel02.

Regarding the first way, I didn't have any issues, I solved the eigenvalue problem and I got the periods of the first five modes. I attach you the model ("Offshore multsec").

Regarding the second way, I use the fiber custom command and I want to add some circular sections as well as some IPE sections. Probably I am doing something wrong here or I don't understand how it works.  What I did is:
![Fiber](https://user-images.githubusercontent.com/71927229/95438785-0d9b0500-0957-11eb-9dbb-863d6bd03639.png)

I also attach you this model named "Offshore fibers" to check what is the problem and it doesn't run the analysis.

I am looking forward to hearing from you.

Kind regards,

Manos Lydakis
MSc student at Denmarks Technical University
[Offshore fibers.gid.zip](https://github.com/rclab-auth/gidopensees/files/5346708/Offshore.fibers.gid.zip)
[Offshore multsec.gid.zip](https://github.com/rclab-auth/gidopensees/files/5346709/Offshore.multsec.gid.zip)

**Comment by iammix** [comment]
Hi Manos,
$startAngle should be 0 and $endAngle 360 in order to create a hollow circular section. Moreover, $numSubdivCirc should be more than 4 and $numSubdivRad more than 3. Please see the attached image.
![image](https://user-images.githubusercontent.com/25987029/96238818-947b5d80-0fa7-11eb-8209-9b788ea60d4b.png)

**Comment by manoslydakis** [comment]
Dear @iammix,

Thank you very much for your response. I changed the values of fiber sections, as you suggested, and it worked! 

At this point, I want to go further and make a time history analysis using accelerograms in both models. Firstly, I did it for the model with the elastic beam-column elements and it worked perfectly. However, when I follow the same procedure for the model where I used fiber sections the analysis does not run due to converge errors. More specifically, this message is shown:

WARNING: analysis .. existing StaticAnalysis exists => wipeAnalysis not invoked, problems may arise
(2) Newton Time 0.01000 WARNING: CTestRelativeEnergyIncr::test() - failed to converge 
after: 100 iterations
NewtnRaphson::solveCurrentStep() -the ConvergenceTest object failed in test()
DirectIntegrationAnalysis::analyze() - the Algorithm failed at time 0.01
OpenSees > analyze failed, returned: -3 error flag
Initial step is divided by 2

I attach the model again as well as the accelerogram used. Thanks in advance for your kind assistance.

Best regards,
Manos Lydakis

[Offshore fibers TH.gid.zip](https://github.com/rclab-auth/gidopensees/files/5396309/Offshore.fibers.TH.gid.zip)
[North.txt](https://github.com/rclab-auth/gidopensees/files/5396313/North.txt)

**Comment by iammix** [comment]
In my opinion you should try a smaller time-step(0.001 or 0.005) and you should try "Total Relative Norm Displacement Increment Test" (aka RelativeTotalNormDispIncr) with a 1e-3 tolerance instead of RelativeEnergyIncr.

HINT: time-step of the analysis can be smaller than the time-step of the accelerogram and RelativeEnergyIncr is not recommended.

**Comment by manoslydakis** [comment]
Dear @iammix,

Finally, I want to investigate if the structure has non-linear behavior under these seismic loads. For that reason, I plotted several moment-curvature graphs from some nodes of the main column and I assumed that if this plot has a linear shape the structure doesn't enter the non-linear range and vise versa. In that way, when I plot the Total_rotation_y over Moment_y I get the left graph which looks completely linear. However, I also plotted the Plastic_rotation_y over My and I got the second (right) graph, where I don't understand exactly what it is. Since the total rotation-moment graph has a linear shape, I thought that I will not get any plastic rotations. Do I miss something here? When I plot the total rotations or displacements, the plastic ones are supposed to be included, right?

![Mom-curv graph](https://user-images.githubusercontent.com/71927229/96706840-675bf000-1397-11eb-9465-4c69334162a0.png)
    
Hopefully, these are my last questions. Thank you in advance for your time!

Kind regards,

Manos Lydakis

**Comment by iammix** [comment]
The reason why I do not prefer Energy Test Criteria is that you should be very careful with the constrain handler. In case that you have Penalty constrain handler, additional large forces exist on the right-hand side of the motion equation(ExternalForces), something that can causes convergence failure (even though the solution might have converged, results are not correct). Newton-Raphson with line search seems ok, however, I would prefer to use Full Newton-Raphson, with Relative Norm Displacement Increment.

Your assumptions about the nonlinear response are totally correct. 
You can say that your response is linear because your Total_Rotation_y over Moment_y is linear.
Something that you missed in the second graph is the values of the rotation that you have. In civil engineering problems, these types of values for rotation are actually zero. Finite element programms cannot print absolute zero due to numerical integrations.

Total displacements and total rotations consist of the elastic and plastic part.  So, yes when you plot total displacements or total rotations you see the sum of them.

Hope this helps,
Konstantinos

**Comment by manoslydakis** [comment]
Dear Konstantinos,

That helped me a lot. Thank you very much for your kind assistance. I really appreciate it.

Kind regards,
Manos Lydakis

**Comment by gordanagg** [comment]
Dear @iammix 

Can you help me with example about nonlinear reversed cyclic static analysis on beam-column joint? I can't get a proper solution...
[Tutorial 4.pdf](https://github.com/rclab-auth/gidopensees/files/5431516/Tutorial.4.pdf)



[tutorial-beam.column.gid.zip](https://github.com/rclab-auth/gidopensees/files/5431420/tutorial-beam.column.gid.zip)
