### ISSUE TITLE
Analysis Crashed or Could not Run

### ISSUE THREAD

**Issue by rriquelme-eng** [rclab-auth/gidopensees#141]
I am trying to run some of the available examples (from version 2.7.0) in version 2.8.0 (plane truss and plane frame) but always I get problems, Analysis Crashed or Analysis Could not Run... In previous issues I read such problems occurs due to compatibility between GID 2.8.0 and Opensees 3.2.2.  Is it rigth? Can someone share Opensees 3.2.1?

Thanks

**Comment by iammix** [comment]
In the link below you can find OpenSees 3.2.1
[https://we.tl/t-NIFuqx1fB5](url)

**Comment by vpapanik** [comment]
Have you seen 'Older OpenSees versions' in issue list ?

**Comment by vpapanik** [comment]
https://www.dropbox.com/sh/uau7mcb8zuwk2fc/AABcQxlVv0fNb5Imw2kZmvN1a?dl=0

**Comment by rriquelme-eng** [comment]
Thanks, but the link is not available.

**Comment by rriquelme-eng** [comment]
Dear Proffesor, thanks a lot

I am downloading the previous version and I will try to fix the issue.

Best

**Comment by DonaldDUT** [comment]
HI, have you got the  Opensees 3.2.1 from others already? if yes, could you please share that CUZ i  have the same trouble like you now. and this is my email: tangyachao@mail.dlut.edu.cn   thanks a lot!

**Comment by luca-cro** [comment]
Hi everyone, I'm having lots of problem with this GiD version. Can someone tell me the right version of Gid and the related OpenSees version? I had a lot of try by mixing them with no results.
Even though,  I have to say that the only way I managed to launch an analysis is with GiD 15.0.1, OpenSees 3.1.0 and GiD+Opensees interface 2.8.0.
The problem is that the analysis starts but it breaks with the eigenvalues analysis. 
Someone help me!

**Comment by vpapanik** [comment]
Your configuration is fine. Send your model in order to test it.

**Comment by luca-cro** [comment]
Correct, the configuration is fine, I managed to run on simple self-made model. Now I'm having problems with the example found on YT: https://www.youtube.com/watch?v=uMrDXUNJu4c&t=595s
I think the problem is the definition of master and slaves nodes beacuse of the little differences that there are between tutorial version and mine.
By the way that's my model, hope you can help me.
Thanks a lot

[3D Frame (static and modal analysis).gid.zip](https://github.com/rclab-auth/gidopensees/files/5466334/3D.Frame.static.and.modal.analysis.gid.zip)

**Comment by vpapanik** [comment]
This is a rather old video, a lot of things have changed since then. Please study the user manual for the proper definition of master/slave nodes.
