### ISSUE TITLE
Use GiD+OpenSees postprocessor

### ISSUE THREAD

**Issue by charden74** [rclab-auth/gidopensees#16]
Hello, 

I am working on a tcl file which uses an algorithm to generate or delete quad and/or SSPquad elements throughout the analysis steps, and is therefore not possible to run in GiD+OpenSees. However, I would still like to use Gid+OpenSees to visualize the data. Is there a sample tcl script that can prepare the necessary msh and other files from the output, to work with the GiD+Opensees problem type and postprocessor? I would really like to use this excellent program!

Thank you, Chad

**Comment by vpapanik** [comment]
Hello Chad,

unfortunately this is not possible at the moment. In order to visualize data on the GiD postprocessor you need to manually create the .msh mesh file, together with the analysis results post.res.

Since your mesh is changing all the time, I think that this is somehow difficult to do even manually.
