### ISSUE TITLE
auto equal and auto zero length element

### ISSUE THREAD

**Issue by aliyaghfoori** [rclab-auth/gidopensees#199]
hi  dear
I want to assign zero-Length element. Since the zero-length elements should be assigned between two nodes with the same coordinates, I have problem with selection of nodes one by one to define different restrains for each one(in 3D soil model). I have same problem when I want to use periodic boundary condition in model.
thanks.

**Comment by iammix** [comment]
Given your situation, here are two approaches you can consider to address these challenges:

**1. Using Different Layers for Each Set of Nodes:** If you're having trouble selecting nodes individually due to their close proximity or identical coordinates, you can try organizing your nodes into different layers. By assigning nodes to different layers, you can then apply different restraints or boundary conditions to each layer as needed. This approach can help you manage and differentiate between closely located nodes.

**2. Making Nodes Slightly Different:** Another approach is to intentionally perturb the coordinates of the nodes that are meant to be identical. By making the coordinates of these nodes slightly different (e.g., by adding a small offset), you can distinguish them while still maintaining their close proximity. This can help address issues related to selecting nodes individually and applying different restraints or boundary conditions. Regarding the warning from OpenSees about nodes not being in the same coordinates, it's important to note that while this warning may appear due to the close proximity of nodes, it typically does not affect the numerical calculations. As long as the nodes are close enough to be considered identical for the purposes of applying zero-length elements or periodic boundary conditions, the numerical results should remain accurate.

**Comment by aliyaghfoori** [comment]
Hi dear 
thank you.
I want to define the lysmer boundary condition in the 2D soil model. in the first step, I defined 3 nodes with the same coordinate. one of them is fixed and the other is freed in the x and y direction respectively (for defining dashpot in the normal and tangent directional). I used viscous material and zerolength elements. when I recorded acceleration or other responses in nodes, the response was incorrect. my procedure to define lysmer dashpot at each node is correct? thanks
