### ISSUE TITLE
problem  

### ISSUE THREAD

**Issue by wbellotta** [rclab-auth/gidopensees#24]
Hi all,
sorry for bother  you with my question below. I'm practicing with Gid-Opensees and I've some problem to solve
After I've created a 3D model, I've  assigned the rigid diaphragm master node and the Rigid  diaphragm slave nodes for each level. Then I've assigned   any  loads ( ground motion in both direction XX-YY  loaded inside the procedure and  the mass at every rigid diaphragm master node) . At last  I've  tried to  run the  analysis but  the warning shown  below appears. 
Coud anybody  help me please.
Thanks in advance
walter bellotta
![error-message](https://user-images.githubusercontent.com/32549896/31240222-32d4abbe-aa00-11e7-8ca0-6d00c1088300.JPG)

**Comment by theokart** [comment]
**For each** rigid diaphragm (floor) you must assign **one** master node and the slave nodes. These must have the same ID number. First floor > ID=1 , Second Floor > ID=2 etc.. 
Moreover, fixities of the master node are implemented automatically in the tcl file depending on the Rigid plane selected of the slave nodes condition with the same ID number, so you do **not** need to assign restraints.

You probably assigned more than one master nodes with identical ID. Inside each condition window, you can see where you have assigned it as well as the field values selected, using the _Entities_ option at the bottom of the window. This will help you find the problem. Otherwise, just reassign the master/slave node conditions carefully (they will be overwritten) considering what i mentioned above.

**Comment by wbellotta** [comment]
I've just controlled   the model the way  you've suggested     ( you can see the immages attached ) and tryed again to run the analysis. 
The warning appears again like the pictures below  show .
I think may be I've made  other mistakes but I don't know where.
thanks for your help.
walter


![slave-nodes](https://user-images.githubusercontent.com/32549896/31267955-80150a70-aa7a-11e7-8f7c-5be68143b46f.JPG)
![master-nodes](https://user-images.githubusercontent.com/32549896/31267960-854d4a20-aa7a-11e7-99bb-2fed34dae3c7.JPG)
![model-warning analysis](https://user-images.githubusercontent.com/32549896/31267961-873cfa2e-aa7a-11e7-9c48-10240a06ac96.JPG)

**Comment by wbellotta** [comment]
I apologize  Theo, I've just closed and reopened the SW and now the problem seems to be overcome.
Thanks a lot for your support.
walter
