### ISSUE TITLE
Creating visco-elastic boundary around soilmedium in 2D and 3D model

### ISSUE THREAD

**Issue by aminkotb** [rclab-auth/gidopensees#25]
I am trying to model 2D and 3D model for soil domain, and I need to apply an artificial boundary around soil mesh in form of visco-elastic boundary (spring and dashpot ) at each node. 
Is there any fast way to apply it to all nodes at the edges?
I have tried to use zero elements but I receive this error message "zero length elements must be assigned to at least 2 nodes" ( whats the step for assigning a zero length element in gid-opensees?

**Comment by theokart** [comment]
ZeroLength ID must be identical the for at least 2 nodes, in order to connect them with zerolength element. In ZeroLength window you can see what you have applied using the Entities option. if more than 2 nodes, the zeroLength is applied on node pairs. 
For your problem, i think you need zeroLength using dashpots at the boundaries and body constraint (equalDOF) between the boundary nodes. Have in mind that body constraint can be applied on a line object (belonging to a surface or/and volume) and then be transferred to all boundary nodes after mesh is generated.

**Comment by sadeghebrahimi** [comment]
Dear GiD+OpenSees team;
I have the same problem.
I was faced with this error: "ZeroLength Element with only 1 node. ZeroLength elements must be assigned to at least 2 nodes."
How can I define 2 points at the same location?
