### ISSUE TITLE
Fiber section definition blanked

### ISSUE THREAD

**Issue by sismo68** [rclab-auth/gidopensees#49]
When defining a simple portal frame (2D) and setting 'forced based BeamColumn' elements, the re is a couple of things:
-the number of integration points are hard set to '3' , this should be open to the user, why is this variable 'fixed' ?
- When defining the section, it is possible to select from the drop down menu 'fiber' or 'fiber custom' but there is no place to define the concrete types (confined, unconfined) the cover and core divisions of the fiber section or even the rebar fibers. However, when exploring the tcl generated file, a fiber section is written in the file that seems to be hard coded, because is the same section no matter what the section dimensions are.
please see attached tcl file
Regards

EM

**Comment by vpapanik** [comment]
- The number of integration points is fixed to 3 for compatibility with GiD postprocessing. Nonetheless, it's always better to have a larger number of elements with 3 GPs instead of fewer elements with more GPs.

- 'fiber' is for predefined sections, and 'fibercustom' are for more complex sections where the user provides the script. The materials are already there to select from. I can't see any problem on this. Do you 'update' your section after you change its data ?

- There's no attached tcl file

**Comment by vpapanik** [comment]
Oh I see, you are referring to the element definition. You should go to the fiber section definition first (5th button on the leftmost toolbar column). Then assign fiber or fibercustom section to the force-based element.

**Comment by Santiagocmac** [comment]
Mr @vpapanik ,

I have been trying to use the function "Fiber Custom" to create a circular hollow section but is not clear for me how should I input the parameters that I nedd.

Thank you very much,
