### ISSUE TITLE
static load and dynamic load 

### ISSUE THREAD

**Issue by haldarsumanta** [rclab-auth/gidopensees#66]
I have modeled a 1 m length cantilever beam using GiD. I want to apply the static load at the free end of the beam at interval 1. At interval 2, I would like to apply cyclic (sinusoidal) displacement at the free end. I could not find any option to incorporate it. Please suggest.

[test.zip](https://github.com/rclab-auth/gidopensees/files/2561386/test.zip)

**Comment by theokart** [comment]
I guess the static load corresponds to the gravity. Choose Newton-Raphson algorithm with Load control and apply this in a few steps (i.e. 5 steps) and check the option "keep load active..." in the first interval options.  Create a second interval (do not copy conditions) using Transient analysis and select Multiple support excitation as the loading type. Moreover, assign "Sine ground motion", through Loads option determining the period and the duration of this loading, to the free end. (Its not ground motion but it will work for your purposes since it just imposes the desired displacement). Set the analysis duration to greater or equal to the loading duration. Since mass is zero (works like a static analysis), setting analysis duration greater than loading duration is unnecessary. So, add mass (in first interval!) if you want to estimate the dynamic behavior.

**Comment by haldarsumanta** [comment]
> I guess the static load corresponds to the gravity. Choose Newton-Raphson algorithm with Load control and apply this in a few steps (i.e. 5 steps) and check the option "keep load active..." in the first interval options. Create a second interval (do not copy conditions) using Transient analysis and select Multiple support excitation as the loading type. Moreover, assign "Sine ground motion", through Loads option determining the period and the duration of this loading, to the free end. (Its not ground motion but it will work for your purposes since it just imposes the desired displacement). Set the analysis duration to greater or equal to the loading duration. Since mass is zero (works like a static analysis), setting analysis duration greater than loading duration is unnecessary. So, add mass (in first interval!) if you want to estimate the dynamic behavior.

Thanks for your reply. The static load is not gravity. It is a point load applied at beam node. In case of 2nd interval, how to apply a sinusoidal displacement at the specific nodes of the beam?

**Comment by fereshteh2012** [comment]
Dear gid opensees interface team,

When I perform analysis, I encounter a problem, saying that :could not run the analysis, please check generated tcl file!
I work with the latest GID version 14.0.1 and interface version 2.6.0 and I delete the problemtypes/opensees folder to install interface again but it does'nt work.
any help appreciated...
thanks.

**Comment by vpapanik** [comment]
you can use displacement of 1 in that node and use a scaling function as loading
