### ISSUE TITLE
Multiple Model Domains

### ISSUE THREAD

**Issue by navidgholizadeh** [rclab-auth/gidopensees#92]
Dear GiD+OpenSees Software Development Team,

I have developed a simple model using GiD+OpenSees Interface. In this model I have used truss, elasticBeamColumn and ShellMITC4 elements. So when I try to generate the .tcl script, I realize that in the generated script truss elements are created in a 3D-3DOF model domain while others are created in a 3D-6DOF model domain. when I try to run the analysis I face a problem which says the Node IDs in two model domains are identical. Even using equalDOF option did not solve this problem. I have attached the model.
I think there must be two solutions.

1) All of model should be created in 3D-6DOF model domain.
2) The Nodes with same coordinates in different model domains should have different tags in order to use equalDOF command.

So in order to achieve the 1st solution, I realized when program generates mesh, two groups appear in group section which their names are 3DOF and 6DOF. Then I try to assign 6DOF group to all of elements. But when I generate the .tcl script, I realize that all truss elements are back to 3DOF group.
In order to achieve the 2nd solution, I use uncollapse option to duplicate the nodes with same coordinats and then I use equalDOF command. Although eigenvalue analysis runs without any error but the problem is the analysis fails in gravity analysis.

I don't know how to solve these problems. Could you please provide me some guidance on how to use one of these two methods to solve the mentioned problem? (I prefer the first solution)

Best Regards,
Navid

[Model.zip](https://github.com/rclab-auth/gidopensees/files/3181056/Model.zip)

**Comment by theokart** [comment]
Dear Navid,

At the moment, at this case you should care that nodes of trusses ( 3 dof ) should be seperate from other with different number of dof. 

An easy way to fix this problem, with respect to the above attached model' state, is to follow the following steps:
1) Move trusses parallel to z axis (e.g. 1 unit ) Utilities > Move ( Entities type : Lines, Transformation : translation )
2) apply equal dof contraints ( 4 pairs of equaldofs applications ) : check only x,y,z displacements of course.
3) Move trusses back to their position ( e.g. -1 unit to z axis ).
Be careful option "Collapse" during move process should be DISABLED! Otherwise point on identical coordinates will be pasted.
