### ISSUE TITLE
getting error: invalid command name "model" while executing model BasicBuilder -ndm2 -ndf3

### ISSUE THREAD

**Issue by marchxtj** [rclab-auth/gidopensees#97]
Hi,
I'm doing a hysteretic analysis on prestressed concrete frame structure. However,  when I am running the analysis, I am getting an error: invalid command name "model" while executing model BasicBuilder -ndm 2 -ndf 3. 
Please find the attached .gid file.
it would be great if you can suggest me how to fix the problem.
Thanks,

![微信图片_20190702202022](https://user-images.githubusercontent.com/52363939/60512461-30c41700-9d07-11e9-80ab-85d973cab770.png)

[2019.7.2+PB in truss.gid.zip](https://github.com/rclab-auth/gidopensees/files/3349999/2019.7.2%2BPB.in.truss.gid.zip)

**Comment by theokart** [comment]
This error is not appears to me. Although, an error is occured because you use common points/nodes for truss and beam elements ( which have different dofs ). Unfortunately, you have to create two different points/nodes at these positions and connect them between equalDOF condition ( checking ux,uy and/or uz in 3D models ).

This error about command name "model" is NOT occured when running manually OpenSees outside the GiD Interface?

**Comment by begumemte** [comment]
After installing the latest version of GiD+OpenSees, whenever I try to run an analysis I am getting the error: invalid command name "model". I think GiD is not able to read the TCL files because before getting the error, a message appears as "generate .tcl file". The previous versions automatically generated TCL files on running the analyses. Even if I generate the TCL file separately before running the analysis, it does not help. Also, the error mentioned above does not occur if the analysis is run in OpenSees manually which signifies that there is no mistake in the TCL files.
Kindly look into the matter ASAP.
Thank You.

**Comment by vpapanik** [comment]
Please attach your model to check it out. You probably used the GiD menu for executing the analysis instead of the GiD+OpenSees menu.

**Comment by tanevski** [comment]
The error you are getting is because the Wish Application is trying to open the "tcl" filetype. Just change the default application for opening tcl-files like for example notepad or notepad++
